export const HIDE_ADD_BTN = 'HIDE_ADD_BTN';
export const FIX_SCROLLBAR = 'FIX_SCROLLBAR';

export const AUTH_USER = 'AUTH_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const FETCH_POSTCARDS = 'FETCH_POSTCARDS';
export const UPLOAD_POSTCARD = 'UPLOAD_POSTCARD';
export const POSTCARD_MODAL = 'POSTCARD_MODAL';
